### ISSUE TITLE
有个列表转换成数组的问题想请教您

### ISSUE THREAD

**Issue by frankxzq** [B-Xi/TIP_2022_CMFSL#1]
您好，感谢您分享的源代码！看了您的论文收益匪浅！
但是我在运行代码的时候出现了一个问题，就是将4个训练的数据集预处理完之后，在运行CMFSL_UP_main.py需要将列表中的数据转换成array，您在CMFSL_UP_main.py的第74行用了如下语句：source_imdb['data']=np.array(source_imdb['data'])，但是这句在运行中会报错，原因是：ValueError: could not broadcast input array from shape (9,9,145) into shape (9,9)，4个数据集的光谱维度不相等，直接转化成数组会出现问题。请问您在这个地方是怎么解决的呢？

**Comment by ANNAZSH** [comment]
> 您好，感谢您分享的源代码！看了您的论文收益匪浅！ 但是我在运行代码的时候出现了一个问题，就是将4个训练的数据集预处理完之后，在运行CMFSL_UP_main.py需要将列表中的数据转换成array，您在CMFSL_UP_main.py的第74行用了如下语句：source_imdb['data']=np.array(source_imdb['data'])，但是这句在运行中会报错，原因是：ValueError: could not broadcast input array from shape (9,9,145) into shape (9,9)，4个数据集的光谱维度不相等，直接转化成数组会出现问题。请问您在这个地方是怎么解决的呢？
您好，我遇到了同样的问题，请问您解决了吗？

**Comment by ANNAZSH** [comment]
The used OCBS band selection method is referred to https://github.com/tanmlh

**Comment by Dawn-LLL** [comment]
我也遇到了相同问题，想问一下，你们的问题解决了吗？  感谢！！
